name = "sfida60-motivatore"
main = "worker.js"
compatibility_date = "2025-05-04"

[triggers]
crons = ["5 4 * * *", "5 19 * * *"]

[[kv_namespaces]]
binding = "KV"
id = "cc03849214564c358b59c7536ecaf9f9"

[vars]
CHAT_ID = "5283084625"
